# If enabled, CL will disable custom data source handling
secure-mode: false

# Level of information printed to console
# true - more information is printed (for example before every send)
verbose: false

logging:
    # Log player connect event
    # Default: true
    player-connect: true
    # Log player disconnect event
    # Default: true
    player-disconnect: true
# Cache where players logs are stored before we send them to database.
# If connection to database is not available, here are stored until we successfully connect to database
# These settings control triggers for sending cache
cache:
    # When cache hit this number of records, it immediately sends cache (this does not define size of cache itself)
    cache-size-trigger: 20
    # Time in milliseconds before sending cache to database after first record is added to cache
    delay-before-send: 5000
# MySQL Credentials - Please Fill Correctly
database:
    host: ""
    port: "3306"
    database-name: ""
    table-name: "connectionlogger"
    user: ""
    password: ""
    pool-size: 1
    timeout: 5000