# If enabled, CL will dissalow custom database handling
secure-mode: false
logging:
    # Log player connect event
    # Default: true
    player-connect: true
    # Log player disconnect event
    # Default: true
    player-disconnect: true
    # Log plugin shutdown
    # Default: false
    plugin-shutdown: false
# Cache where players logs are stored before we send them to database.
# If connection to database is not available, here are stored until we seccessully connect to database
# Default: 50
cache:
    cache-size: 20
    # Time in miliseconds before sending cache to database
    delay-before-send: 10000
# MySQL Credentials - Please Fill Correctly
database:
    host: ""
    port: "3306"
    database-name: ""
    table-name: "connectionlogger"
    user: ""
    password: ""
    pools: 1
    timeout: 5000