name: ConnectionLogger
main: sk.crafting.connectionlogger.ConnectionLogger
description: Player connection logger
author: kikz0r_sk
version: 1.6
commands:
    cl:
        description: Main command with subcommands
        usage: /cl <print|reload|clear|help|dumpcache>
        permission: connectionlogger.cl
permissions:
    connectionlogger.*:
        description: Gives access to all commands
        children:
            connectionlogger.cl: true