name: ConnectionLogger
main: sk.crafting.connectionlogger.ConnectionLogger
description: Player connection logger
author: kikz0r_sk
version: 1.6
commands:
    cl:
        description: Main command with subcommands
        usage: /cl <print|reload|clear|help|dumpcache|printcache>
        permission: connectionlogger.cl
permissions:
    connectionlogger.*:
        description: Gives access to all commands
        children:
            connectionlogger.cl: true
            connectionlogger.print: true
            connectionlogger.clear: true
            connectionlogger.dumpcache: true
            connectionlogger.help: true
            connectionlogger.printcache: true
            connectionlogger.reload: true
    connectionlogger.cl:
        description: Gives access to CL command
    connectionlogger.cl.print:
        description: Allows to show logs in specified time range
    connectionlogger.cl.clear:
        description: Allows to remove logs
    connectionlogger.cl.dumpcache:
        description: Allows to remove logs
    connectionlogger.cl.help:
        description: Gives access to help
    connectionlogger.cl.printcache:
        description: Allows to print cache
    connectionlogger.cl.reload:
        description: Allows to reload ConnectionLogger