name: ConnectionLogger
main: sk.crafting.connectionlogger.ConnectionLogger
description: Player connection logger
author: kikz0r_sk
version: 1.4
commands:
    cl:
        description: Show connection log
        usage: /cl <print|reload|clear|help|dumpcache> <hours>
        permission: connectionlogger.cl
permissions:
    connectionlogger.*:
        description: Gives access to all commands
        children:
            connectionlogger.cl: true