# Select what you want to be logged
logging:
    # Log player connect event
    player-connect: true
    # Log player disconnect event
    player-disconnect: true
    # Log plugin shutdown
    plugin-shutdown: false
auto-cleaning:
    # Clean logs at server shutdown
    server-shutdown: false
# MySQL Credentials - Please Fill Correctly
database:
    host: ""
    port: "3306"
    database-name: ""
    table-name: "connectionlogger"
    user: ""
    password: ""
    pools: 1